### PR TITLE
Conda dev environment

### LINKED ISSUE #35: Conda environment for algorithm toolkit development
We have seemed to standardize on using conda across most projects at this point. An anaconda environment file to install dependencies for development work on the algorithm toolkit will consequently be useful.

### PR DESCRIPTION
**Pull request by ryanlaclair**
## What?
A simple addition of an anaconda `environment.yml` file for use when doing development work on the algorithm toolkit.

## Why?
BeamIO has seemed to standardize on conda for environment management across projects. Including an environment file in the repo ensures developers making changes to the algorithm toolkit can focus on the code rather than the setup.

Closes #35

### CODE REVIEW

**Review by wrp5031 — COMMENTED** [review]
Will this be a base for the example atk project as well? Or will the example project have its own yml file? If it is used as a base, we should maybe test to make sure Shapely works with Python 3.9. I actually did not even know Python 3.9 was released until now haha.

Also, you are merging a feature branch into master? Was this meant for integration. If meant for master, maybe this should have been a `hotfix` branch

**Comment by ryanlaclair** [comment]
> Will this be a base for the example atk project as well? Or will the example project have its own yml file? If it is used as a base, we should maybe test to make sure Shapely works with Python 3.9. I actually did not even know Python 3.9 was released until now haha

Good point - I didn't originally intend to use it for the example project since that seems to use a regular `requirements.txt` file. However we could update the example project to use `conda` if we want. Even with an update to use `conda` in the example, we shouldn't need to use this as a base - the Algorithm Toolkit runtime dependency libraries should be automatically installed when the ATK is installed. 

This environment file would be used for development work, where you cloning the code from github (does not isntall dependencies) rather than `pip install` (does install dependencies).

**Review by wrp5031 — APPROVED** [review]

**Comment by wrp5031** [comment]
> Good point - I didn't originally intend to use it for the example project since that seems to use a regular `requirements.txt` file. However we could update the example project to use `conda` if we want. Even with an update to use `conda` in the example, we shouldn't need to use this as a base - the Algorithm Toolkit runtime dependency libraries should be automatically installed when the ATK is installed.
> 

I think we should have a conda env yml file for the example project, but that is for another discussion.

**Comment by chriswilley** [comment]
> > Good point - I didn't originally intend to use it for the example project since that seems to use a regular `requirements.txt` file. However we could update the example project to use `conda` if we want. Even with an update to use `conda` in the example, we shouldn't need to use this as a base - the Algorithm Toolkit runtime dependency libraries should be automatically installed when the ATK is installed.
> 
> I think we should have a conda env yml file for the example project, but that is for another discussion.

I would support that, but we should keep requirements.txt in there also for people who don't use conda.

**Review by chriswilley — APPROVED** [review]

**Pull request merged**
